<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

// Create a shortcut for params.
$params = $this->item->params;
JHtml::addIncludePath(JPATH_COMPONENT . '/helpers/html');
$canEdit = $this->item->params->get('access-edit');
$info    = $params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));

$string = htmlentities($this->item->title, null, 'utf-8');
$title = str_replace("&nbsp;", " ", $string);
$title = html_entity_decode($title);

?>

<article class="card post-wrapper">
	<div class="thumb-wrapper waves-effect waves-block waves-light card-image image-responsive">
		<?php echo JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>
	</div>
	
	<div class="blog-content card-content">
		<header class="entry-header-wrapper sticky">
            <div class="entry-header">
				<h2 class="entry-title"><?php echo $title; ?></h2>
			</div>
		</header>
		
		<?php if (!$params->get('show_intro')) : ?>
			<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
			<?php echo $this->item->event->afterDisplayTitle; ?>
		<?php endif; ?>

		<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
		<?php echo $this->item->event->beforeDisplayContent; ?>
		<div class="entry-content">
			<?php
			$string = htmlentities($this->item->introtext, null, 'utf-8');
			$content = str_replace("&nbsp;", " ", $string);
			$content = html_entity_decode($content);
			?>
			<p><?php echo $content; ?></p>
		</div>

		<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
		<?php echo $this->item->event->afterDisplayContent; ?>

	</div>
</article>