//CATEGORIES
export const LIST_ALL_CATEGORIES = "LIST_ALL_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const FETCH_CATEGORIES_INFO = "FETCH_CATEGORIES_INFO";

//STORIES
export const LIST_ALL_STORIES = "LIST_ALL_STORIES";
export const ADD_STORY = "ADD_STORY";
export const DELETE_STORY = "DELETE_STORY";
export const FETCH_STORIES = "FETCH_STORIES";
export const FETCH_STORY = "FETCH_STORY";
export const EDIT_STORY = "EDIT_STORY";
export const UPDATE_STORY = "UPDATE_STORY";
export const FETCH_STORIES_PREVIEW = "FETCH_STORIES_PREVIEW";
export const FILTER_STORIES = "FILTER_STORIES";

//USER
export const FETCH_USER = "FETCH_USER";
